Hero-mobile-style-first-addition
TaniaUdod/project-group-8 pull request #2
Opened 2023-07-07 18:35 UTC by shevchenkoiryna88

Наброски hero-mobile

2023-07-07 22:08 UTC, TaniaUdod requested changes
для mobile:    
1)виправити<div class="container hero-container">2).hero-container видалити max-width: 1280px; margin: 0 auto
3).hero-face-list задати position: relative
2).hero-div-face-one left: 42px;
2).hero-div-face-two left: 71px;
3).hero-titel видалити font-family: DM Sans; font-style: normal;
4).hero-text видалити font-family: DM Sans; font-style: normal; font-weight: 400;
5).hero-btn видалити cursor: pointer;
6).hero-nav видалити height: 80px; 
7).hero-nav змінити max-width: 173px; 
8).hero-nav дописати margin-bottom: 20px;
9).hero-nav-list видалити height: 60px;
10).hero-nav-link дописати display: flex; align-items: center;
11):root видалити з hero.css

2023-07-08 08:56 UTC, TaniaUdod requested changes
для mobile:
1)виправити div class="container hero-container"
2)окремо скачати IMG_9620 1 (розміри 230 x 228), за нею зробити span і створити із заданими стилями овальний прямокутник
3)для блоку.hero-nav передивися попередній коментар
4)face-2x не спрацьовують

2023-07-08 15:36 UTC, shevchenkoiryna88 commented
не знаю, як зробити картинку на бекграунд, як її правильно обрізати.

2023-07-08 18:46 UTC, TaniaUdod approved these changes

2023-07-08 18:46 UTC, merged